name: Issue Duplicate Checker

on:
  issues:
    types: [opened, edited]

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write 
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run AI Detector
        uses: ./ 
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          pinecone_api_key: ${{ secrets.PINECONE_API_KEY }}
          pinecone_index_name: ${{ secrets.PINECONE_INDEX_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}